development:  
  adapter: postgresql
  encoding: unicode
  database: learnerslist_development
  pool: 5
  username: magnusbenoni
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: learnerslist_test
  pool: 5
  username: magnusbenoni
  password:
